POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZvcmVtYW42V2Fsc2giLCJpZCI6IjYyMzlmMDA5ODExOTU2MzJiODEwNTAwYiIsImlhdCI6MTY0ODA1MjIyNX0.8NSrJ5Kv5UfCaOnfV7Cn6tx1XCj0Qm8tdbrDaJwAL7g

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 2
}

###
GET http://localhost:3003/api/blogs
Accept: application/json

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 2
}

###
DELETE http://localhost:3001/api/blogs/5a422bc61b54a676234d17fc

###
PUT http://localhost:3003/api/blogs/623b4bd8ee8737039c96e7fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZvcmVtYW42V2Fsc2giLCJpZCI6IjYyMzlmMDA5ODExOTU2MzJiODEwNTAwYiIsImlhdCI6MTY0ODA1MjIyNX0.8NSrJ5Kv5UfCaOnfV7Cn6tx1XCj0Qm8tdbrDaJwAL7g

{
  "title": "Type wars",
  "author": "Robert C. Martin Lol",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 2
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZvcmVtYW42V2Fsc2giLCJpZCI6IjYyMzlmMDA5ODExOTU2MzJiODEwNTAwYiIsImlhdCI6MTY0Nzk2NDE4NH0.M-mBeZRO_k3jwsYppYXHlFYUfp1SpCcZ6oBIChM6F4Q

{
  "title": "Type wars 1",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 2,
  "user": "60af547efca4023168ce2988"
}

###

DELETE http://localhost:3003/api/blogs/60b48c5d2e4d19382cfb9b35
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZvcmVtYW42V2Fsc2giLCJpZCI6IjYwYWY1NDdlZmNhNDAyMzE2OGNlMjk4OCIsImlhdCI6MTYyMjQ0NDc2MH0.RoJkDh3QmQd101RVp2AtOWDm4-ksvVCzzXoIG0JiE-k
###


# curl -H "Content-Type: application/json; charset=utf-8"  -H "Authorization: Bearer ya29.a0ARrdaM-5lKWelgi5uHhnahzzGFyrHM7EPGM6_j1VwcyqztJzHt3F_BQzcdyJEBnDU2ytC_XSbFZ-gzyAkO0yDXSRMM2Y8USItLQmfin-NWTin8OiyTeJIHoANIYx89ds2sAZ2w3VnfVfnUiLwk8C0qf314_X9zWWSMI-Pw50lpjgiTrpa3u_sWhatb-eYTpXtLlylYXcu6PWoHuVr8UsTk0Np-ZyRasgM03TicLt1FPt5g"  -d "{\"queryInput\":{\"text\":{\"text\":\"Any good plan recommendation\",\"languageCode\":\"en\"}},\"queryParams\":{\"source\":\"DIALOGFLOW_CONSOLE\",\"timeZone\":\"Asia/Calcutta\",\"sentimentAnalysisRequestConfig\":{\"analyzeQueryTextSentiment\":true}}}" "https://dialogflow.googleapis.com/v2/projects/hale-structure-350211/agent/sessions/3eb6d903-8fea-86b9-9ab1-d43956255e5b:detectIntent"
POST https://dialogflow.googleapis.com/v2/projects/hale-structure-350211/agent/sessions/3eb6d903-8fea-86b9-9ab1-d43956255e5b:detectIntent
Authorization: Bearer ya29.a0ARrdaM-5lKWelgi5uHhnahzzGFyrHM7EPGM6_j1VwcyqztJzHt3F_BQzcdyJEBnDU2ytC_XSbFZ-gzyAkO0yDXSRMM2Y8USItLQmfin-NWTin8OiyTeJIHoANIYx89ds2sAZ2w3VnfVfnUiLwk8C0qf314_X9zWWSMI-Pw50lpjgiTrpa3u_sWhatb-eYTpXtLlylYXcu6PWoHuVr8UsTk0Np-ZyRasgM03TicLt1FPt5g
Content-Type: application/json; charset=utf-8

{
  "queryInput": {
    "text": {
      "text": "Any good plan recommendation",
      "languageCode": "en"
    }
  },
  "queryParams": {
    "source": "DIALOGFLOW_CONSOLE",
    "timeZone": "Asia/Calcutta",
    "sentimentAnalysisRequestConfig": {
      "analyzeQueryTextSentiment": true
    }
  }
}

###

